plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tvbox.ipgateway'
    compileSdk 34

    defaultConfig {
        applicationId "com.tvbox.ipgateway"
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName "3.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
